version: '3'
services:
  sqlserver_historic:
    build:
      context: ./compose/sqlserver_historic
      args:
       - BASEIMAGE=${SQLSERVER_HISTORIC_IMAGE}
    image: ${SQLSERVER_HISTORIC_IMAGE_ROOT}:${STACK_VERSION}
    container_name: ${STACK_NAME:-defstack}_${SQLSERVER_HISTORIC_NAME}
    environment:
      - SA_PASSWORD=${SA_PASSWORD}
      - SQL_RESTORE_ON_START=${SQL_RESTORE_ON_START}
    deploy:
      resources:
        limits:
          cpus: '0.50'
    ports:
      - "${SQLSERVER_HISTORIC_PORT}:1433"
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.sqlserver_historic.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.sqlserver_historic.entrypoints=mssql"
      - "traefik.tcp.routers.sqlserver_historic.service=sqlserver_historic-svc"
      - "traefik.tcp.services.sqlserver_historic-svc.loadbalancer.server.port=1433"
    networks:
     - mydefaultstack

  sqlserver_current:
#    image: ${SQLSERVER_CURRENT_IMAGE}
    image: ${SQLSERVER_HISTORIC_IMAGE_ROOT}:${STACK_VERSION}
    container_name: ${STACK_NAME:-defstack}_${SQLSERVER_CURRENT_NAME}
    # environment:
    #   - SA_PASSWORD=${SA_PASSWORD}
    #   - ACCEPT_EULA=Y
    #   - MSSQL_PID=Developer
    environment:
      - SA_PASSWORD=${SA_PASSWORD}
      - SQL_RESTORE_ON_START=false  # disables restore script
    ports:
      - "${SQLSERVER_CURRENT_PORT}:1433"
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.sqlserver_current.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.sqlserver_current.entrypoints=mssql"
      - "traefik.tcp.routers.sqlserver_current.service=sqlserver_current-svc"
      - "traefik.tcp.services.sqlserver_current-svc.loadbalancer.server.port=1433"
    networks:
     - mydefaultstack


volumes:
  persistent_data:
    driver: local

networks:
  mydefaultstack:
    name: mydefaultstack
    external: true
